[build]
target = "index.html"
dist = "dist"
public_url = "/"
wasm_opt = "z"

[wasm_opt]
args = ["--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[watch]
ignore = []

[serve]
port = 8080
open = false
