[build]
target = "index.html"
dist = "dist"
public_url = "/"

[tools.wasm-opt]
version = "116"

[[build.hooks]]
stage = "post_build"
command = "wasm-opt"
command_arguments = ["--enable-bulk-memory", "--enable-nontrapping-float-to-int", "-Oz", "{wasm}", "-o", "{wasm}"]

[watch]
ignore = []

[serve]
port = 8080
open = false
