[build]
target = "index.html"
dist = "dist"
public_url = "/"

[tools.wasm-opt]
version = "116"
args = ["--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[watch]
ignore = []

[serve]
port = 8080
open = false
